### ISSUE TITLE
Crashes when running as non root user

### ISSUE THREAD

**Issue by TheHippo** [dizballanze/do-latency#1]
I'm on Ubuntu 14.04.
```
Latency testing: |                                                                           |0.00%Traceback (most recent call last):
  File "/home/hippo/test/do-check/env/bin/do-latency", line 11, in <module>
    sys.exit(main())
  File "/home/hippo/test/do-check/env/local/lib/python2.7/site-packages/do_latency/do_latency.py", line 55, in main
    start_test(**args.__dict__)
  File "/home/hippo/test/do-check/env/local/lib/python2.7/site-packages/do_latency/do_latency.py", line 34, in start_test
    results[region].append(do_ping(host, count=ping_count, udp=True, hook=lambda: pbar.update(1)))
  File "/home/hippo/test/do-check/env/local/lib/python2.7/site-packages/do_latency/ping.py", line 21, in do_ping
    return ping.run(count).avg_rtt
  File "/home/hippo/test/do-check/env/local/lib/python2.7/site-packages/pyping/core.py", line 271, in run
    delay = self.do()
  File "/home/hippo/test/do-check/env/local/lib/python2.7/site-packages/pyping/core.py", line 296, in do
    current_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.getprotobyname("icmp"))
  File "/usr/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 13] Permission denied
```

**Comment by francescortiz** [comment]
Same error, even with sudo or su, on ArchLinux.

**Comment by dizballanze** [comment]
Thanks for the issue!
I have added parameter `--udp` as optional feature. It should work with `sudo` now.

**Comment by TheHippo** [comment]
Works as root user for me.

**Comment by francescortiz** [comment]
Yes, now it works with sudo. Thank you!
